#!/bin/sh -e

. /usr/share/debconf/confmodule

db_fget base-passwd/update-passwd isdefault
if [ "$RET" = "true" ]; then
    db_set base-passwd/update-passwd true
fi

# Ask about automatic updating.

db_input low base-passwd/update-passwd || true
db_go

db_get base-passwd/update-passwd
if [ "$RET" = "false" ]; then
    db_input low base-passwd/refused-update || true
    db_go
fi
