#!/bin/sh

pkg=base-passwd

if [ ! "$1" = "configure" ]; then
    exit 0
fi

if [ -d /usr/doc -a ! -e /usr/doc/$pkg -a -d /usr/share/doc/$pkg ] ; then
    ln -s ../share/doc/$pkg /usr/doc/$pkg
fi

if [ ! -e /etc/passwd ] ; then
	cp /usr/share/base-passwd/passwd.master /etc/passwd
fi

if [ ! -e /etc/group ] ; then
	cp /usr/share/base-passwd/group.master /etc/group
fi

echo "Checking if your system passwd, shadow and group files are correct..."

answer=""
if ! update-passwd --dry-run ; then
	cat <<EOF

It looks like I need to make some changes to your system. Without those
changes some packages might not work correctly. The list of changes are
listed above. For more documentation on the Debian account policies
please read /usr/share/doc/base-passwd/README.

EOF
	while : ; do
		echo -n "Should I update your system? [Y/n] "
		read a
		if [ "$a" = "" ] ; then
			a="y"
		fi
		a=`echo $a | tr A-Z a-z`
		if [ "$a" = "y" -o "$a" = "n" ] ; then
			break
		fi
		echo "Illegal answer"
	done
fi

if [ "$a" = "y" ] ; then
	echo "Okay, I am going to make the necessary updates now"
	update-passwd --verbose
elif [ "$a" = "n" ] ; then
	cat <<EOF

Okay, I will not update your system. If you want to make this update later
please check the update-passwd utility.

EOF
fi

#if grep "ftp:.*:11:" /etc/passwd > /dev/null; then
#	echo "Moving user ftp to uid 999."
#	update-passwd --sanity-check --move-ftp;
#else
#	update-passwd --sanity-check
#fi
